### ISSUE TITLE
M1 - Manager Screen

### ISSUE THREAD

**Issue by eileenrob84** [djackso2/burnt_popcorn#1]
As a Manager user of the app, I want a Manager Screen that provides all of the functionality I will need to maintain accountability and maximize Employee safety during an Emergency Event.

Development branch: M1

Success criteria: 
1. All structures shown in the wireframes are present (don't need to be functional, just there)
2. Page can be accessed without crashing the program
3. Page and code are reviewed (through pull request) by at least one other team member

Test procedure:
1. Run the client application
2. Navigate to the Manager page (through debug-only buttons)
3. Verify that all buttons from the wireframes are present: P / F
4. (Descoped and moved to M1.A, not required for this story) Verify that the drop-down for group selection is present and works (will be dummy for now):  P / F
5. Verify that the scroll list of people is present in the center of the page and can scroll up and down (dummy for now):  P / F
6. Verify that the "BURNT POPCORN" label at the top of the page has changed to a user's name (will be dummy for now):  P / F

**Comment by djackso2** [comment]
Ran test procedure, no issues. Branch reviewed by Courtney and Eileen. Branch merged.
