### ISSUE TITLE
M1.7 - Manager User Options

### ISSUE THREAD

**Issue by eileenrob84** [djackso2/burnt_popcorn#12]
As a Manager, I want to be able to manage available Manager User Options directly from within the application so that I don't need administrator support for basic options.

**Comment by djackso2** [comment]
Added ManagerOptionsPage, Completed Edit Employee popup, tested all added functionality with no issues (simple code exercise), reviewed by Andy.

Note: conflicts with .kv file were resolved by hand. Code rechecked out and re-tested to verify manual edits.
