### ISSUE TITLE
update the development plan

### ISSUE THREAD

**Issue by eileenrob84** [djackso2/burnt_popcorn#43]
update the dev plan to show current state

use change tracking
10/25/2018 - updated plan was presented to Prof. Vesonder during class

**Comment by rawallis** [comment]
Since Google Docs doesn't have change-tracking like Word does, I've highlighted my changes. So far, we've been pretty close to our original plan.

**Comment by eileenrob84** [comment]
Thanks

**Comment by cthaden** [comment]
I added the version of Twilio to the Dev Plan.
