### ISSUE TITLE
M1.3 - Manager manual employee status update

### ISSUE THREAD

**Issue by eileenrob84** [djackso2/burnt_popcorn#8]
As a Manager, I want to update Employee status during an Emergency Event manually when the Alerted Employee is physically present or provides status info in a manner other than via the application so that I can reduce network and system load when possible.

**Comment by djackso2** [comment]
Implemented a custom popup to show selectable statuses and call the server to change them based on selection. 
Implemented on branch G6_Dan, awaiting manual merge with that group. 

Success criteria: Manager is able to press a Button (no more than two manual gestures) to update a selected employee's status from the central view scroll list.

Test procedure: Exercise the function above for all four types of status ( Safe, Not Safe, Not Yet, and No Contact) for at least two employees. Verify no employees show without a label and button color in the central scroll list before and after the status update. 

Tested 18Nov18 by DKJ on G6_Ref. PASS
